app:
  name: "go-kafka"
  # values: localhost, staging, production
  env: "localhost"
  version: "0.1.0"

http:
  port: "8000"
  cors: true

logger:
  logLevel: "debug"
  rollbarEnv: "go-kafka"

mysql:
  url: "mysql:password@tcp(localhost:3306)/go_kafka?parseTime=true"

kafka:
  brokers: ["localhost:9092"]
  groupID: go-kafka
  initTopics: true

kafkaTopics:
  eventCreated:
    topicName: task_created
    partitions: 10
    replicationFactor: 1

kafkaPublisherConfig:
  topic: event_created
  topicPrefix: eventStore
  partitions: 3
  replicationFactor: 1
